### PR TITLE
WP-212 feat(Palette): New blue required by the Editor's Pick

### PR DESCRIPTION
**Pull request by garySiladi**

### CODE REVIEW

**Comment by umbobabo** [comment]
What is the story you are working on?
Why we need a new color on the palette?

**Comment by garySiladi** [comment]
WP210(Substory WP212). 
We discussed it with @russEco, because a new color code in his design.

screen shot 2016-09-29 at 10 41 22 am

**Comment by russEco** [comment]
We have specified a few more colours that we need for some elements will talk through it with you.

**Comment by umbobabo** [comment]
Np.
I don't have any problem adding colors. It's a design choice.
What I would like to point here that a PR should have an appropriate title more than "Added new color to the palette" something like "New red required by the Editor's pick".

**Comment by garySiladi** [comment]
Ok, right no we are working on those subtasks seperately. We worked on WP-212 Primary so we added just one color that that subtask needs.

**Comment by yasgreen93** [comment]
LGTM 👍

**Pull request merged**
