### PR TITLE
Peer review request

### PR DESCRIPTION
**Pull request by fabiosantoscode**
This is not a peer review for that single-line commit :trollface: . Instead, it's for the whole repository.

So, my dear peers, please review :)

### CODE REVIEW

**Comment by umbobabo** [comment]
If you run npm lint 2 errors are throwned:

example.es6
  3:1  error  Use of future reserved word in strict mode

index.es6
  1:1  error  Illegal import declaration

Pls, review that is doable the rest is fine.
We probably will need to review this component to automate the update of it in the component-library, but this is out-of-scope for this PR.

**Comment by fabiosantoscode** [comment]
The linter is most certainly broken.

The first error refers to my use of `let` to create a variable.

The second error refers to `import React from 'react'`, which is a perfectly valid import declaration.

**Comment by fabiosantoscode** [comment]
Ok, I've changed everything so it follows the react/strict standards.

**Comment by fabiosantoscode** [comment]
Ok, it's done!

**Pull request merged**
